### ISSUE TITLE
On edit, file field always null if not reselect midia image

### ISSUE THREAD

**Issue by ladhadha** [itskodinger/midia#13]
My scenario is on updating data. Below are my code for Midia implementation field:
```
@if(!empty($banner->image))
     <img
        src="{{ $banner->image }}"
        id="image-prev"
        width="100%"
        alt="">
@else
    <img id="image-prev" width="100%"/>
@endif
<div class="input-group col-xs-12">
    {!! Form::text('image', null, [
        'class' => 'form-control file-upload-info',
        'id'    => 'image_desktop'
    ]) !!}
    <span class="input-group-append">
        <a
            href="javascript:;"
            class="midia-toggle file-upload-browse btn btn-primary"
            data-input="image_desktop"
            data-preview="image-prev">Select File</a>
    </span>
</div>
```
On creating scenario, it works perfectly. But on update, when I submit the form without reselect the image from Midia instance, it will submitted as null value. Also, it always removing src attribute of preview image element. I think the problem comes from this [line](https://github.com/itskodinger/midia/blob/master/src/Public/midia.js#L379) and this [line](https://github.com/itskodinger/midia/blob/master/src/Public/midia.js#L382). It removes both value and image preview src. Any idea how to do this correctly?

**Comment by ladhadha** [comment]
Any way my quick fix is by comment out those lines. Just wonder if Midia has any purpose to do both cleaning operation.

**Comment by nauvalazhar** [comment]
Thank you for opening the issue, I will check and fix it later.

**Comment by nauvalazhar** [comment]
This issue fixed. Thanks to @mrofi
