### ISSUE TITLE
Required ClipboardJS

### ISSUE THREAD

**Issue by kamranata** [itskodinger/midia#16]
Hi,

When I tried to use with tinyMce I got error "ClipboardJS is not defined". I see you use it, but doesn't included it. Please fix that

**Comment by nauvalazhar** [comment]
Hi, thank you. We'll fix it as soon as possible.

**Comment by kamranata** [comment]
I added this line
`<script src="{{asset('vendor/midia/clipboard.js')}}"></script>`

But still get error "ClipboardJS is not defined"

**Comment by kamranata** [comment]
I found problem :) In midia/src/View/app.blade.php file you didn't used clipboardjs
