### ISSUE TITLE
Can't create thumbnail of big images

### ISSUE THREAD

**Issue by tpaksu** [itskodinger/midia#20]
Hello, 

I'm uploading images which have for example 1.5MB in size and 2560x1024 pixel dimensions. The script can't create thumbnails of it. Didn't check yet, but it works in smaller images. Did one of you experience and solve something about this issue?

**Comment by tpaksu** [comment]
It turns out that it isn't related with image size, but it's caused by the missing mime types on the list:

        // Resize
        $is_image = [
            'image/jpg',
            'image/jpeg',
            'image/pjpeg',
            'image/png',
            'image/x-png',
            'image/gif',
            'image/webp',
            'image/x-webp'
        ];

I'll create a pull request with this.

**Comment by tpaksu** [comment]
Pushed this in #21

**Comment by nauvalazhar** [comment]
Thank you!
