### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by tpaksu** [itskodinger/midia#22]
Hi, can you tag a new release with the latest code? I want to use a release instead of the master branch  :) :1st_place_medal:

**Comment by nauvalazhar** [comment]
Can you help me to write a changelog? 😄

**Comment by tpaksu** [comment]
:) Ok I'll prepare one

**Comment by tpaksu** [comment]
### Fixed:
- Removed closure in config file, which caused the config not to be cached by Laravel
- Added ClipboardJS script to loaded scripts in modal view
- Created the upload directory when it doesn't exists, instead of triggering a 404 error
- Added missing mime types for image checks before creating the thumbnails

### Updated:
- Added option to select initial value 
- Added localization support
- Added `midia_get_thumbnail($url, $size)` helper method to retrieve the image thumbnail with the desired size

**Comment by tpaksu** [comment]
Btw it's working in Laravel 5.7. You can add it to readme too.

**Comment by nauvalazhar** [comment]
Ok, thank you

**Comment by nauvalazhar** [comment]
Done! https://github.com/itskodinger/midia/releases/tag/v1.3.0

**Comment by tpaksu** [comment]
Thank you :)

**Comment by tpaksu** [comment]
Did you forget to update packagist? composer still picks the 1.2 version.

**Comment by nauvalazhar** [comment]
Done!

**Comment by tpaksu** [comment]
Thank you very much sir :)
