### ISSUE TITLE
Add URL image information in image preview

### ISSUE THREAD

**Issue by ladhadha** [itskodinger/midia#7]
First of all, I would say thank you for creating this awesome package. Honestly I am using this package at a project of mine :).

I think it will be good if there are information or the url how each image accessed showed in the Midia image preview (see image below):
![midia](https://user-images.githubusercontent.com/11268333/43149214-222eafb8-8f91-11e8-8c66-df19a3ced8b9.png)

It will very helpfull for non technical person so they know how to access the image after uploading. Another improvement suggestion of this case is how about adding "copy url" button or when clicking the image title it goes directly to the image url?

**Comment by nauvalazhar** [comment]
Hi, thank you for using this package. I think it would be nice to add the 'Copy URL' button for UX which is better and easier to understand for non-technical people. Thanks for your suggestion, I will add it as soon as possible :)

**Comment by nauvalazhar** [comment]
Hi, your feature request has arrived :) Please, check in the new version!
https://github.com/itskodinger/midia/releases/tag/v1.2.0
